name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      skip_tests:
        description: 'Skip tests before release'
        required: false
        default: false
        type: boolean

jobs:
  manual-release:
    name: Manual Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        if: github.event.inputs.skip_tests != 'true'
        run: npm run lint

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version
        id: version_bump
        run: |
          VERSION_TYPE="${{ github.event.inputs.version_type }}"
          echo "Bumping $VERSION_TYPE version..."

          # Bump version and capture the new version
          NEW_VERSION=$(npm version $VERSION_TYPE --no-git-tag-version)
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"

      - name: Commit version bump
        run: |
          git add package.json package-lock.json
          git commit -m "chore: bump version to ${{ steps.version_bump.outputs.new_version }} [skip ci]"
          git push

      - name: Create tag and trigger release
        run: |
          NEW_VERSION="${{ steps.version_bump.outputs.new_version }}"
          echo "Creating tag: $NEW_VERSION"

          git tag -a "$NEW_VERSION" -m "Release $NEW_VERSION"
          git push origin "$NEW_VERSION"

          echo "🚀 Tag created: $NEW_VERSION"
          echo "Release workflows will be triggered automatically."
